version: '3.8'

services:
  app:
    build: .
    container_name: comandei
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - MONGOOSE=mongodb://mongo:27017/comandei
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: comandei_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  expo:
    image: node:lts-alpine
    container_name: comandei_mobile
    working_dir: /app
    volumes:
      - ./MOBILE:/app
    networks:
      - app_network
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: >
      sh -c "
        yarn global add expo-cli &&
        expo start --tunnel"

networks:
  app_network:

volumes:
  mongo_data:
